name: Feature Request
description: Suggest a new feature for Hippo
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: phase
    attributes:
      label: Development Phase
      description: Which phase does this feature belong to?
      options:
        - Phase 1: Visual Polish & Consistency
        - Phase 2: Smart Tagging & Organization
        - Phase 3: Advanced Search & Discovery
        - Phase 4: Smart Automation
        - Phase 5: Platform & Integrations
        - Other / Not Sure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: I would like Hippo to...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: This would help me...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?
      placeholder: I tried...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would like to work on this feature
        - label: I can help test this feature
        - label: I can help document this feature
